### ISSUE TITLE
API documentation copy URL has "//"

### ISSUE THREAD

**Issue by kkrypt0nn** [top-gg/docs#35]
#### Expected Behavior

Get the link `https://top.gg/api/bots` copied after clicking on the "Copy URL" button of the API documentation.

#### Observed Behavior

Got the link `https://top.gg/api//bots` copied after clicking the button.

#### Applicable Links or Attachments

https://docs.top.gg/api/bot

#### Steps to Reproduce

1. Open docs.top.gg
2. Click on the `Bot` or another resource where you can copy a link
3. Click on "Copy link"

#### Web Browser and Version

Microsoft Edge - 90.0.818.62 Official build) (64-bit)

#### Operating System and Version

Windows 10

#### Screen Resolution

3440x1440

#### Additional Information/Comments

It's not a big deal, as the URL is still considered as valid.

**Comment by Xetera** [comment]
Feel free to open a PR for this one yourself if you've got time. Most likely related to https://github.com/top-gg/docs/blob/master/src/components/HTTPHeader.jsx#L67. We should be using the [new URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) constructor with a second argument to prevent duplicate slashes with url concatenation.

**Comment by kkrypt0nn** [comment]
A PR has been done, there was nothing big to do beside removing a `/` if I understood correctly. See PR #37

**Comment by kkrypt0nn** [comment]
Issue fixed and merged.
