### ISSUE TITLE
(what I believe to be) emoji doesn't render on Bot model

### ISSUE THREAD

**Issue by EEKIM10** [top-gg/docs#58]
https://docs.top.gg/api/bot/#bot-structure: ![image](https://user-images.githubusercontent.com/53234499/132983599-c90d7934-ce19-4f35-b1ef-47acb6914a70.png)

I believe this is supposed to render as ⚠️?

Browser: Chromium 93.0.4577.63 (Official Build) Arch Linux (64-bit)

**Comment by ExtremeDevelopments** [comment]
It's meant to be rendered as a warning symbol. I am working on a PR already for it ^-^

**Comment by ExtremeDevelopments** [comment]
Also #45

**Comment by Luke-6723** [comment]
This was fixed by https://github.com/top-gg/docs/pull/65 can now be closed
